apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: demo-clusters
  namespace: apriltag
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      myname: lucifer