apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: demo-clusters
  namespace: rhacm-policies
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
    matchLabels:
      myname: lucifer